CREATE TABLE [dbo].[OperationItem]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [OperationId] INT NOT NULL, 
    [Z1] NVARCHAR(50) NULL, 
    [Z2] NVARCHAR(50) NULL, 
    [Z3] NVARCHAR(50) NULL, 
    [ZEDrawingNumber] NVARCHAR(50) NULL, 
    [FileName] NVARCHAR(50) NULL, 
    [Symbol] NVARCHAR(50) NULL,
    [AMT] INT NULL,
    [SheetNumber] NVARCHAR(50) NULL,
    [StockName] NVARCHAR(500) NULL,
    [SupplierName] NVARCHAR(500) NULL,
    [SupplierPartNumber] NVARCHAR(500) NULL,
    [ItemNumber] NVARCHAR(500) NULL,
    [ReferanceZENumber] NVARCHAR(50) NULL,
    [ReferanceSymbol] NVARCHAR(50) NULL,
    [ReferanceSheetNumber] NVARCHAR(50) NULL,
    [FileIdentificationType] int NULL,
    [HEXNumber] NVARCHAR(10) NULL,
    [NewSymbol] NVARCHAR(50) NULL,
    [NewSheetNumber] NVARCHAR(50) NULL,
    [RowIndex] INT NULL,
    [Column1] NVARCHAR(50) NULL,
    [Column2] NVARCHAR(50) NULL,
    [Column3] NVARCHAR(50) NULL,
    [IsProcessed] BIT NULL DEFAULT 0, 
    [Status1] BIT NULL DEFAULT 0,
    [Status2] BIT NULL DEFAULT 0,
    [Status3] BIT NULL DEFAULT 0,
    [Status4] BIT NULL DEFAULT 0,
    [Status5] BIT NULL DEFAULT 0,
    CONSTRAINT [FK_OperationItem_LineOperation] FOREIGN KEY ([OperationId]) REFERENCES [LineOperationMaster]([OperationId])
)
